# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.16.4
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Derive velocities from PPP outputs
#
# TO DO:
#
# - **This is currently functional as a notebook only!**
# - convert into something operational, ideally split into Level-1 and Level-2 datasets.
# - Determine the highest temporal resolution plausible for le5s single-frequency data.
# - Properly formatted outputs following usual gnssice format
#
#
# (Re-)uses as many components of our existing (Track-based) workflow as possible.
#
# This script was developed for processing le5s 2025 data, which suffered from poor clock precision and so were only PPP-processed at single-frequency. These data are completely unprocessable by Track.
#
# Inputs:
#
# - A folder containing (daily) CSV and POS files generated by the Canadian PPP service. These need to have already been unzipped by the user.
#
# Filtering strategy for le5s data:
#
# - We can't use the normal sigma cut-offs approach developed for Track outputs, because the sigmas are too big.
# - Instead we apply direct cut-offs to the x and y sigma (95%) values provided by PPP.
# - And we delete entire days containing insufficient numbers of observations.
# - To further reduce the noise floor we have the option of calculating velocities over durations > 1 day.
#
# Andrew Tedstone, August 2026

# %%
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import dask.dataframe as dd
import os

from gnssice import pp
import math

sns.set_context('paper')


args = {
    'site': 'le5s'
}

#p = Path(f'/Users/atedston/scratch/flowstate-gnss-processing/{args["site"]}')
p = Path(os.path.join(os.environ['GNSS_L1DIR'], args['site']))

path_output_L2 = os.path.join(os.environ['GNSS_L2DIR'], args['site'])

# %%
args['site']

# %% [markdown]
# ## Load and organise PPP outputs

# %%
# Load the CSV files, which contain decimal degrees coordinates
ddf = dd.read_csv(p / '*/*.csv')
df_csv = ddf.compute()

# Load the POS files, which don't have decimal degrees but do have sigmas info
# To fix!: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
ddf = dd.read_csv(p / '*/*.pos', sep=r'\s+', skiprows=3, 
                  parse_dates={'ts':['YEAR-MM-DD','HR:MN:SS.SS']}, 
                  date_format={'YEAR-MM-DD':'%y-%m-%d', 'HR:MN:SS.SS':'%H:%M:%S.%f'})
df_pos = ddf.compute()

# Check that the dataframes match precisely in length
assert len(df_csv) == len(df_pos)

# Use the timestamps created from the POS files to set the index of the CSV 
df_csv.index = df_pos.ts
df_pos.index = df_pos.ts

# Now sort both on index
df_csv = df_csv.sort_index()
df_pos = df_pos.sort_index()

# The PPP outputs contain a single row for the next day, which results in duplicated time stamps
# ...remove them.
df_csv = df_csv[~df_pos.index.duplicated()]
df_pos = df_pos[~df_pos.index.duplicated()]

# Renaming 
mapping = {
    'latitude_decimal_degree':'Latitude_deg',
    'longitude_decimal_degree':'Longitude_deg',
    'ellipsoidal_height_m':'Height_m',
    'day_of_year':'DOY',
    'year':'YY'
}

# Do the renaming
df_csv = df_csv.rename(mapping, axis=1)

# Remove the following columns
drop = ['rcvr_clk_ns', 'decimal_hour']
df_csv = df_csv.drop(columns=drop)

# %%
# Calculate fractional DOY (for correspondence with TRACK outputs)
fdoy = (df_csv.index.day_of_year) + ((df_csv.index - df_csv.index.floor('D')) / pd.Timedelta(24, 'h'))
df_csv['Fract_DOY'] = fdoy

# Calculate daily seconds elapsed (for correspondence with TRACK outputs)
daily_seconds_elapsed = (df_csv.index - pd.to_datetime(df_csv.index.date)).total_seconds()
df_csv['Seconds'] = daily_seconds_elapsed

# Add the needed POS columns into the CSV frame
df_csv['SigmaE_95%_m'] = df_pos['SDLAT(95%)']
df_csv['SigmaN_95%_m'] = df_pos['SDLON(95%)']
df_csv['SigmaH_95%_m'] = df_pos['SDHGT(95%)']

# %% [markdown]
# ### Initial cleaning

# %%
# Plot the east sigmas to get an idea of their magnitude
plt.figure()
df_csv['SigmaE_95%_m'].plot()

# %%
# Do some basic cleaning by filtering on the basis of standard deviation chosen by manual iteration
pos_cln = df_csv[(df_csv['SigmaN_95%_m'] < 0.25) & (df_csv['SigmaE_95%_m'] < 0.25)]

# Remove days with less than threshold number of observations, threshold based on previous manual examination
nobs = pos_cln.Longitude_deg.resample('1D').count()
pos_cln.loc[:,'daily_nobs'] = nobs.resample('10s').ffill()
pos_cln = pos_cln[pos_cln['daily_nobs'] > 500]

# %%
# Compare the uncleaned and cleaned data
fig, ax = plt.subplots()
df_csv.plot(x='Longitude_deg', y='Latitude_deg', marker='.', linestyle='none', ax=ax)
pos_cln.plot(x='Longitude_deg', y='Latitude_deg', marker='.', linestyle='none', alpha=0.2, color='tab:orange', ax=ax)

# %%
# Compare the uncleaned and cleaned data
fig, ax = plt.subplots()
plt.plot(df_csv.index, df_csv['Longitude_deg'], marker='.', linestyle='none')
plt.plot(pos_cln.index, pos_cln['Longitude_deg'], marker='.', linestyle='none', alpha=0.2, color='tab:orange')
plt.grid()

# %%
# Compare the uncleaned and cleaned data
fig, ax = plt.subplots()
plt.plot(df_csv.index, df_csv['Latitude_deg'], marker='.', linestyle='none')
plt.plot(pos_cln.index, pos_cln['Latitude_deg'], marker='.', linestyle='none', alpha=0.2, color='tab:orange')
plt.grid()

# %%
# Compare the uncleaned and cleaned data
fig, ax = plt.subplots()
plt.plot(df_csv['Longitude_deg'], df_csv['Latitude_deg'], marker='.', linestyle='none')
plt.plot(pos_cln['Longitude_deg'], pos_cln['Latitude_deg'], marker='.', linestyle='none', alpha=0.2, color='tab:orange')
plt.grid()

# %% [markdown]
# ### Rotate into local coordinate frame
#
# This uses existing workflow functionality

# %%
# Get the local origin coordinate
prexyz = pp.ell2xyz(pos_cln['Latitude_deg'].iloc[0:100]*(math.pi/180), 
                            pos_cln['Longitude_deg'].iloc[0:100]*(math.pi/180), 
                            pos_cln['Height_m'].iloc[0:100])

# %%
# Calculate local north-east-up
neu = pp.calculate_local_neu(pos_cln, 
     prexyz['x_m'].mean(), 
     prexyz['y_m'].mean(), 
     prexyz['z_m'].mean(), 
     pos_cln.Latitude_deg.iloc[0:100].mean(), 
     pos_cln.Longitude_deg.iloc[0:100].mean())

# %%
neu

# %%
# Find direction of along-track flow and rotate data along it
neu['Fract_DOY'] = pos_cln['Fract_DOY']
directions = pp.calculate_displacement_trajectory(neu)
r1 = pp.create_rot_matrix(directions)
disp = pp.rotate_to_displacements(neu['East_m'], neu['North_m'], r1)
# Add Z series back in
disp.loc[:,'z_m'] = neu['z_m']

# %%
# Plot a check graphic to verify performance of rotation
# %matplotlib widget
plt.figure()
disp['x_m'].plot(marker='.', linestyle='none')
plt.ylabel('Along-track displacement (m)')

# %% [markdown]
# ### Derive velocities

# %% [markdown]
# #### Quick/simple

# %%
# Calculate daily midday position (this gets around severe quality issues often found at start and end of each daily PPP window)
# This is the simplest approach...
# daily_midday = xy.resample('1D').apply(lambda x: x.where((x.index.hour >= 9) & (x.index.hour <= 15)).mean())

# # %matplotlib widget 
# plt.figure(figsize=(8,4))
# (daily_midday['x_m'].diff()*-1*365.25).plot(drawstyle='steps-post')
# (daily_midday['x_m'].diff()*-1*365.25).interpolate().plot(drawstyle='steps-post', linestyle=':', color='tab:blue')
# plt.ylabel('m yr-1')
# plt.title('le5s')
# plt.grid()
#plt.xlim('2025-07-01','2025-09-01')

#(daily_midday['x_m'].diff()*-1*365.25).to_csv('/Users/atedston/Dropbox/work/papers/gerber_apres/le5s_2025_ppp_velocity_alpha_v2026-08-19.csv')

# %%
# Simple height time series
plt.figure(figsize=(8,4))
h = disp.z_m.rolling('24h', center=True).mean()
h.resample('10min').first().plot(marker='.')
plt.ylabel('height (m)')
plt.grid()
plt.xlim('2025-07-01','2025-09-01')
h.resample('10min').first().to_csv('/Users/atedston/Dropbox/work/papers/gerber_apres/le5s_2025_ppp_height_alpha_v2026-08-20.csv')

# %% [markdown]
# #### Testing velocities using gnssice functionality

# %%
disp['SigmaE_95%_m'] = pos_cln['SigmaE_95%_m']
disp['SigmaN_95%_m'] = pos_cln['SigmaN_95%_m']
#xyz['z_m'] = pos_cln['Height_m']

## Smoothing
# Restore to original frequency and interpolate; adds a flag column named 'interpolated'
filtd_i = pp.regularise(disp, '10s')

# Do Gaussian filtering - this df does not have interpolated column
# We smooth over a 12 hour window instead of the usual 6 hours given the noise of the PPP single-freq solution
filtd_disp = pp.smooth_displacement(filtd_i, 
                                    21600*2, 
                                    gauss_win_z_mult=4
                                   )

# Sub-set data to retain only original data samples (modified by Gaussian filtering)
xyz = filtd_disp.filter(items=('x_m', 'y_m', 'z_m'), axis='columns')
xyz['interpolated'] = filtd_i['interpolated'].astype(bool)


# %%
# %matplotlib widget
plt.figure()
xyz.x_m.plot()
filtd_disp.x_m.plot()
plt.grid()

# %%
# Supply the smoothed and interpolated x values, but the unsmoothed, uninterpolated sigma values.
v24h_epoch = pp.calculate_epoch_velocities_and_uncertainties(filtd_disp['x_m'], pos_cln['SigmaE_95%_m'], pos_cln['SigmaN_95%_m'], '24h', window='3h')
v3d_epoch = pp.calculate_epoch_velocities_and_uncertainties(filtd_disp['x_m'], pos_cln['SigmaE_95%_m'], pos_cln['SigmaN_95%_m'], '3D', window='3h')
v5d_epoch = pp.calculate_epoch_velocities_and_uncertainties(filtd_disp['x_m'], pos_cln['SigmaE_95%_m'], pos_cln['SigmaN_95%_m'], '5D', window='3h')

# %%
import numpy as np
def epoch_plotting(v_ts, data_kwargs=None, error_kwargs=None):
    # Plot stepped velocities
    plt.plot(v_ts.index, v_ts['v_myr'], drawstyle='steps-post', **data_kwargs)
    # Now plot uncertainties. Note that we cannot use the errorbar call to also plot the velocities,
    # because the steps don't begin in the right places when called with irregularly spaced mid-point timestamps.
    # This is therefore a different situation to that of regularly spaced velocities and uncertainties.
    mid_pt_timestamps = (v_ts.index+np.abs(v_ts.index.diff(-1)/2))
    df_plotting = pd.DataFrame({'v_myr':v_ts.v_myr, 'v_unc':v_ts.v_uncertainty_myr})
    df_plotting.index = mid_pt_timestamps
    df_plotting = df_plotting[df_plotting.index.notnull()]
    df_plotting = df_plotting.dropna()
    plt.errorbar(df_plotting.index, df_plotting['v_myr'], linestyle='none',
                yerr=df_plotting['v_unc'], **error_kwargs)
    
# %matplotlib inline    
plt.figure(figsize=(8,4))
epoch_plotting(v24h_epoch, 
                data_kwargs=dict(color='tab:blue', alpha=0.5),
                error_kwargs=dict(elinewidth=0.5, ecolor='tab:blue', capsize=0, alpha=0.2))
# epoch_plotting(v3d_epoch, 
#                 data_kwargs=dict(color='k', linewidth=2),
#                 error_kwargs=dict(elinewidth=1, ecolor='k', capsize=1))
epoch_plotting(v3d_epoch, 
                data_kwargs=dict(color='k', linewidth=1.5),
                error_kwargs=dict(elinewidth=1, ecolor='k', capsize=1))

plt.grid()
#plt.ylim(ax_lim(v24h_epoch.v_myr,10)) # n is multiple of std dev
plt.title(f'{args["site"]} 1-D and 5-D velocity (observational epoch differencing)')
plt.ylabel('m/yr')
#plt.savefig('%s_v24h_5d_epochs.png' %output_L2_base, dpi=300)

# %%
#v1d_epoch.to_csv(f'/scratch/{args["site"]}_2025_ppp_velocity_1d_epochs.csv')
#v5d_epoch.to_csv(f'/scratch/{args["site"]}_2025_ppp_velocity_5d_epochs.csv')

# %% [markdown]
# ## Export to disk

# %%
# Define output filenames
output_to_pre = '{site}_{ys}_{ds}_{ye}_{de}'.format(
    site=args['site'],
    ys=pos_cln.index[0].year,
    ds=pos_cln.index[0].timetuple().tm_yday,
    ye=pos_cln.index[-1].year,
    de=pos_cln.index[-1].timetuple().tm_yday
)

# Other outputs are appended '_disp' rather than '_geod'.
output_L2_base = os.path.join(path_output_L2, f'{output_to_pre}_disp')
output_L2_H5 =  '%s.h5' %output_L2_base

# Make sure that directory gets created, it may not exist yet
os.makedirs(path_output_L2, exist_ok=True)


# %%
# If there is an existing file, delete it to prevent conflicts.
if os.path.exists(output_L2_H5):
    os.remove(output_L2_H5)
    print('Old main output file found, deleted.')

# %% [markdown]
# ### Save filters info

# %%
# ffile = output_L2_base + '_filter_parameters.yaml'
# with open(ffile, 'w+') as fh:
#     fh.write('# Record of the level-2 filtering parameters used to generate this Level-2 dataset. \n')
#     fh.write('# This is a reference-only file, generated from the defaults YAML and any user-specific YAML. \n')
#     fh.write('# The default filter parameters are found in position 0. \n')
#     fh.write('# Any periods in which different filter parameters were set are listed starting from position 1. \n')
#     yaml.dump(config_sets, fh)

# %% [markdown]
# ### Save displacements

# %%
# Save displacements to disk
xyz.to_hdf(output_L2_H5, key='xyz', format='table')
print('Saved displacements.')
print('Main output file: %s ' %output_L2_H5)

# %% [markdown]
# ### Save velocities

# %%
v24h_epoch.to_hdf(output_L2_H5, key='v_24h_epochs', format='table')
v5d_epoch.to_hdf(output_L2_H5, key='v_5d_epochs', format='table')
#v15d_epoch.to_hdf(output_L2_H5, key='v_15d_epochs', format='table')
v24h_epoch.to_csv('%s_velocity_24h_epochs.csv' %output_L2_base)
v5d_epoch.to_csv('%s_velocity_5d_epochs.csv' %output_L2_base)
#v15d_epoch.to_csv('%s_velocity_15d_epochs.csv' %output_L2_base)


# %%
