# # gnss_vel.py
#
# Process Level-1 GNSS positions into Level-2 displacement and velocity time series,
# from EITHER of two input types:
#
# - `track` : TRACK/GEOD Level-1 parquet file (generated by `export_level1.py`).
# - `ppp`   : NRCan CSRS-PPP daily `.csv` + `.pos` files.
#
# Only data ingestion and filtering differ between the two input types. All other
# steps are shared: local NEU, rotation, pole corrections, exclusions, 
# regularisation, Gaussian smoothing, velocities, export, plots.
#
# Supersedes `gnss_disp_vel.py` (TRACK) and `gnss_ppp_vel.py` (PPP).
#
# ## USAGE
#
#     python gnss_vel.py -h
#
# Or as a Notebook (JupyterLab: right-click -> Open With -> Notebook), putting
# arguments in the 'Running in a Notebook?' cell.
#
# ## DATA INPUTS
#
# Level-1 inputs are looked for in `$GNSS_L1DIR/<site>/`:
# - track: one file matching `pp.REGEX_L1_FILE` (`<site>_YYYY_DOY_YYYY_DOY_geod.parquet`)
# - ppp: `<year>/*.csv` and `<year>/*.pos` (one sub-directory per year). Use -ppp_glob to change.
#
# With `-input auto` (default), the parquet is used if present, otherwise PPP files.
#
# Options files, looked for in `$GNSS_L2DIR/<site>/` (or -optspath):
# - `origin_<site>.csv` : mandatory for track. For ppp, if absent, the origin is
#   the mean of the first 100 epochs that pass the PPP filters (not saved).
# - `rotation_<site>.dat` : created if absent. For track, from all Level-1 epochs;
#   for ppp, from the epochs that pass the PPP filters.
# - `exclusions_<site>.csv`, `pole_corrections_<site>.csv` : optional.
#
# Filter parameters (YAML):
# - Default: `level2_parameter_defaults.yaml` (track) or `level2_parameter_defaults_ppp.yaml` (ppp),
#   both in the package directory. Override with -f.
# - Temporal adjustments: -tf. Supported keys: track -> filter_positions_episodic,
#   filter_positions_continuous, remove_displacement_outliers; ppp -> filter_positions_ppp.
#
# ## OUTPUTS (in `$GNSS_L2DIR/<site>/`)
# - `<site>_YYYY_DOY_YYYY_DOY_disp[_PPP].h5`, velocity CSVs, filter-parameters YAML, plots.
#   PPP outputs carry a `_PPP` suffix so they never overwrite TRACK outputs of the same period.
#
# ## HISTORY
# - Based on `plot_site_rel_2009_2012_geod.m` (Matt King, Andrew Sole, Ian Bartholomew, Andrew Tedstone, 2009-2012).
# - `gnss_disp_vel.py` created 2022-07-27 AJT, various updates to Sep 2026 - most important:
# - New epoch-by-epoch velocities calculations, Nov. 2025, AJT.
# - Moved filter parameters to YAML files, Dec. 2025, AJT.
# - Added new average-based processing for short daily observation blocks, Sep. 2026, AJT.
# - `gnss_ppp_vel.py` created August 2026 AJT.
# - Merged into `gnss_vel.py`, Sep. 2026.
#

import pandas as pd
import os
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import argparse
from copy import deepcopy
from glob import glob
import math
import yaml
import re

from gnssice import pp, ppp

# ## Input parameters

# +
p = argparse.ArgumentParser('Kinematic GPS: filter positions, calculate \
    trajectories, calculate velocities. Accepts TRACK parquet or PPP csv/pos \
    inputs. Output .h5 files of displacements, CSV files of velocities, plots of data.')
p.add_argument('site', type=str, help='Name/identifier of site')
p.add_argument('-input', type=str, default='auto', choices=['auto', 'track', 'ppp'],
               help='Level-1 input type. auto: use TRACK parquet if present, otherwise PPP csv/pos.')
p.add_argument('-ppp_glob', type=str, default='*',
               help='Glob (relative to $GNSS_L1DIR/site) of the directories holding PPP .csv/.pos files. Default: * (year sub-directories).')
p.add_argument('-f', type=str, default=None, help='Location of YAML Filter file containing default filter parameters. \
    Defaults to level2_parameter_defaults.yaml (track) or level2_parameter_defaults_ppp.yaml (ppp) in installation directory.')
p.add_argument('-tf', type=str, default=None, help='Location of YAML Temporal Filter file containing filter parameters for specific temporal periods.')
p.add_argument('-legacy', action='store_true', help='Output velocities calculated using "legacy" (Edin. 2009-13) approach.')
p.add_argument('-optspath', type=str, default=None, help='Location of options files (origin, exclusions...) if \
    not $GNSS_L2DIR')
p.add_argument('-noexcl', action='store_true', help='Disable excluding user-specified periods based on exclusion CSV file.')
p.add_argument('-nocorrect', action='store_true', help='Disable apply pole corrections based on corrections CSV file.')
p.add_argument('-noplot', action='store_true', help='Do not generate plots.')
p.add_argument('-stake', action='store_true', help='Short-occupation stake mode. \
    Do not apply any filtering or smoothing operations. This is useful for \
    processing short-occupation fixes.')
p.add_argument('-tz', type=str, help='Localise v_24h to the specified timezone.')
p.add_argument('-sample_freq', type=str, default='10s')
p.add_argument('-v6h', action='store_true', help='Compute sliding 6h velocities for the site.')

p.add_argument('-nbplot', type=str, default='widget', help='If running as a Notebook, \
               defines the matplotlib backend used. Supply widget or inline.')
print('')
# -

# ### Running in a Notebook? Put your parameters in below!

# +
# If running as a Notebook, provide your arguments to the ArgumentParser here.
# These arguments are only read when running as a Notebook, otherwise they are ignored.

# Examples:
# A continuous TRACK site with no extra options:
# input_args = ['lev5']
# A PPP site (auto-detected because it has no Level-1 parquet), or forced:
# input_args = ['ilhn', '-input', 'ppp']
# A stake only site:
# input_args = ['f004', '-stake']
# Output both epoch (new-style) and legacy (old-style) velocities, without pole corrections
# input_args = ['lev5', '-legacy', '-nocorrect']
# Arguments with additional inputs
# input_args = ['lev5', '-tf', 'path/to/my_file.yaml', '-legacy']

input_args = ['le5w', '-tf', '/scratch/flowstate-gnss-level2/le5w/le5w_temporal_filter_track.yaml']


# -

# ## Identify execution mode

# +
def is_notebook() -> bool:
    """stackoverflow.com/"""
    try:
        shell = get_ipython().__class__.__name__
        return shell == 'ZMQInteractiveShell'
    except NameError:
        return False

if is_notebook(): 
    print('Notebook mode')
    args = p.parse_args(input_args)
    if args.nbplot == 'widget':
        print('widget')
        # %matplotlib widget
    elif args.nbplot == 'inline':
        print('inline')
        # %matplotlib inline
    else:
        raise ValueError('Unknown matplotlib backend specified for Notebook. Only widget or inline are understood (provided %s)' %args.nbplot)
    # %load_ext autoreload
    # %autoreload 2
    # %aimport gnssice
else:
    print('Terminal mode')
    args = p.parse_args()

# +
path_output_L2 = os.path.join(os.environ['GNSS_L2DIR'], args.site)
print(f'Level-2 Directory: {path_output_L2}')

# By default, find the options files (e.g. exclusions) in the Level-2 directory.
if args.optspath is None:
    args.optspath = path_output_L2
# -

# ## Identify Level-1 input type

# +
level1_path = os.path.join(os.environ['GNSS_L1DIR'], args.site)

# Candidate TRACK parquet files
l1_parquet = [f for f in os.listdir(level1_path) if re.match(pp.REGEX_L1_FILE, f)]
# Candidate PPP files
ppp_csv_glob = os.path.join(level1_path, args.ppp_glob, '*.csv')
ppp_pos_glob = os.path.join(level1_path, args.ppp_glob, '*.pos')
n_ppp_csv = len(glob(ppp_csv_glob))
n_ppp_pos = len(glob(ppp_pos_glob))

if args.input == 'auto':
    if len(l1_parquet) > 0:
        input_type = 'track'
    elif n_ppp_csv > 0 and n_ppp_pos > 0:
        input_type = 'ppp'
    else:
        raise FileNotFoundError(f'No TRACK Level-1 parquet or PPP csv/pos files found in {level1_path}.')
else:
    input_type = args.input
print(f'Input type: {input_type}')

# PPP outputs are suffixed so that they cannot overwrite TRACK outputs.
sfx = '_PPP' if input_type == 'ppp' else ''
# -

# ## Load configuration/options

# +
def read_yaml(fn):
    with open(fn) as cf_file:
        return yaml.safe_load(cf_file.read())

default_yaml = {'track': 'level2_parameter_defaults.yaml',
                'ppp': 'level2_parameter_defaults_ppp.yaml'}
if args.f is None:
    fn = Path(os.path.abspath(pp.__file__)).parent / default_yaml[input_type]
else:
    fn = args.f
print(f'Filter parameters file: {fn}')
config = read_yaml(fn)

# And also read the temporal filter file, if one is provided
pfc = read_yaml(args.tf) if args.tf is not None else None
# -

# ## Load Level-1 data

# +
if input_type == 'track':
    if len(l1_parquet) > 1:
        raise ValueError(f'More than one Level-1 file found: {l1_parquet}')
    elif len(l1_parquet) == 0:
        raise FileNotFoundError(f'No Level-1 parquet file found in {level1_path}.')
    f = l1_parquet[0]
    print(f'Loading Level-1 file: {f}...')
    geod = pd.read_parquet(os.path.join(level1_path, f.strip()))
    geod = pp.update_legacy_geod_col_names(geod)

elif input_type == 'ppp':
    print(f'Loading PPP files: {n_ppp_csv} csv, {n_ppp_pos} pos...')
    csv = ppp.read_csv(ppp_csv_glob)
    pos = ppp.read_pos(ppp_pos_glob)
    # Renames to TRACK column names: Latitude_deg, Longitude_deg, Height_m, SigN_cm, SigE_cm, SigH_cm, Fract_DOY...
    geod = ppp.to_track_format(csv, pos)
    del csv, pos

print(f'{len(geod)} epochs loaded, {geod.index[0]} to {geod.index[-1]}')


# -

# ## Input-specific quality filters
#
# These functions contain the only processing which differs between input types.
#
# The functions are located here because `filter_ppp` is needed for calculating the PPP origin point.

# +
def filter_ppp(df, fcfg):
    """ Filtering for PPP positions.

    1. Retain epochs with 95% sigmas below threshold (the TRACK RMS/N/NotF 
       approach is not possible, and PPP sigmas are too large for TRACK thresholds).
    2. Remove days that have insufficient observations after (1).
    """
    c = fcfg['filter_positions_ppp']
    n = len(df)
    print(f'\t Starting with {n} positions')
    df = df[(df['SigN_cm'] < c['sig_n_cm']) & (df['SigE_cm'] < c['sig_e_cm'])]
    print(f'\t {len(df)} left after sigma filter')
    daily_nobs = pd.Series(1, index=df.index).groupby(df.index.floor('1D')).transform('count')
    df = df[daily_nobs > c['min_daily_obs']]
    print(f'\t {len(df)} ({np.round(100 / max(n, 1) * len(df), 0)} %) left after removing days with <= {c["min_daily_obs"]} obs')
    return df


def average_positions(df, freq='1D', dim_cols=['x_m', 'y_m', 'z_m', 'SigN_cm', 'SigE_cm'], 
                   default_reducer='mean', extra_reducers=['std'], trim=None):
    """
    Calculate average values by integrating over the desired frequency.

    Intended use is to take short GNSS observation periods (a few hours)
    and average the position estimates into a single value for the period,
    for each of the positional dimensions.

    :param df: pd.DataFrame
    :param freq: str, desired output frequency
    :param dim_cols: list, names of columns containing the position dimensions.
    :param extra_reducers: list, name of pandas reduction methods to also run besides mean.
    :param trim: str, time amount (e.g. 1h) to trim from each side of period before averaging.

    Returns: pd.DataFrame, with columns as indicated in dim_cols (means); 
    other statistics in columns appended with name of statistic.
    """
    def _midpts(x):
        if len(x) > 0:
            start = x.index[0]
            finish = x.index[-1]
            midpt = start + ((finish - start) / 2)
            return midpt.round(args.sample_freq)
        else:
            return np.nan

    if trim:
        df = df.loc[df.index[0]+pd.Timedelta(trim):df.index[-1]-pd.Timedelta(trim)]
    # Get timestamps of midpoint in each resampled block
    midpts = df[dim_cols[0]].resample(freq).apply(_midpts)
    midpts.name = None

    store = []
    for dim in dim_cols:
        for method in ([default_reducer] + extra_reducers):
            rs = df[dim].resample('1D').apply(method)
            rs.index = midpts
            # time blocks submitted for resampling which do not contain data return NaT: get rid of these
            rs = rs[rs.index.notna()]
            rs.name = dim if method == default_reducer else f'{dim}_{method}'
            store.append(rs)
        
    return pd.DataFrame(store).T


def filter_track(data_here, fcfg):
    """ Filtering for TRACK positions.

    Identifies periods of continuous, daily/episodic and no occupation, 
    then applies the corresponding filtering to each period.
    Returns list of filtered DataFrames.
    """
    def occ_type(d, threshold_continuous=1600):
        """ Label occupation type from number of observations per day.
        2 = continuous (e.g. 10 sec) occupation, 1 = 'episodic', e.g. for an hour, 0 = no occupation
        """
        if d > threshold_continuous: return 2
        if d < threshold_continuous and d > 0: return 1
        return 0

    def process_daily_occups(df):
        """ The filtering processes for episodic/daily observations. """
        # First cull based on 'standard' TRACK statistics
        if df['RMS_mm'].isna().sum() < 1:
            df = pp.filter_positions(df, 
                                     fcfg['filter_positions_episodic']['rms'],
                                     fcfg['filter_positions_episodic']['h'],
                                     fcfg['filter_positions_episodic']['N'], 
                                     fcfg['filter_positions_episodic']['NotF']
                                    )
        else:
            print('Found NaNs in RMS_mm column, skipping filter_positions')
        if len(df) == 0:
            print('No positions left after initial filtering')
            return df
        # Now calculate single means per day of occupation
        # The idea here is that poor quality days can be identified by high standard deviations.
        means = average_positions(df, trim='1h')
        if len(means) == 0:
            means = average_positions(df)
        th = fcfg['filter_positions_episodic']['stddev']
        keep = means[(means['x_m_std'] < th) & (means['y_m_std'] < th)]
        print(f'{len(keep)} positions left after daily averaging')
        return keep

    def process_cont_occups(df):
        """ The filtering processes for continuous observations. """
        print('Filtering out bad positions (according to RMS etc)')
        n = len(df)
        print(f'\t Starting with {n} positions')
        df = pp.filter_positions(df, 
                     fcfg['filter_positions_continuous']['rms'],
                     fcfg['filter_positions_continuous']['h'],
                     fcfg['filter_positions_continuous']['N'], 
                     fcfg['filter_positions_continuous']['NotF']
                    )
        nn = len(df)
        print(f'\t {nn} ({np.round(100 / n * nn, 0)} %) left after applying filter criteria')
        if nn == 0:
            return df
        df = pp.remove_displacement_outliers(df, 
                                             args.sample_freq,
                                             fcfg['remove_displacement_outliers']['diff_x_m'],
                                             fcfg['remove_displacement_outliers']['diff_y_m'],
                                             fcfg['remove_displacement_outliers']['diff_z_m'],
                                             fcfg['remove_displacement_outliers']['median_win'],
                                             fcfg['remove_displacement_outliers']['sigma_mult'],
                                             iterations=fcfg['remove_displacement_outliers'].get('iterations', 2)
                                            )
        nnn = len(df)
        print(f'\t {nnn} ({np.round(100 / n * nnn, 0)} %) left after removing displacement outliers')
        return df

    data_ok = data_here[data_here.exclude == False]
    out = []

    # Count number of daily observations
    counts = data_ok.x_m.resample('1D').count().to_frame()
    counts['type'] = counts['x_m'].apply(occ_type)
    counts['type_roll'] = counts['type'].rolling('3D', center=True).max()

    # Find change dates
    detect = np.abs(counts['type_roll'].shift(1) - counts['type_roll'])
    dates = detect[detect > 0].index.to_list()

    # Get associated period types
    period_types = counts['type_roll'][detect > 0].to_list()

    # Create equivalent 'starting' lists that include the first period's type
    period_types_start = deepcopy(period_types)
    period_types_start.insert(0, counts['type_roll'].iloc[0])
    dates_start = deepcopy(dates)
    dates_start.insert(0, data_here.index[0])

    # Add dummy values to make lists same size as _start variants
    period_types.append(0)
    dates.append(0)

    # Process each identified period of data in turn.
    for d_st, d_en, s in zip(dates_start, dates, period_types_start):
        
        # Get the data from this period...
        if d_en == 0:
            pxyz = data_ok[d_st:]
            d_en = data_ok.index[-1]
        else:
            # pandas indexing is inclusive, so to prevent using the same data twice we
            # need to force the indexing to be 'exclusive'.
            d_en = d_en - pd.Timedelta(days=1)
            if s == 2:
                pxyz = data_ok[d_st:d_en]
            elif s == 1:
                # Try to add a couple of days from the continuous time series, to improve rolling window smoothing.
                pxyz = data_ok[d_st:d_en+pd.Timedelta(days=2)]
            elif s == 0:
                pxyz = data_ok.iloc[0:0]
            else:
                raise ValueError('Unknown occupation type.')

        message = 'Period {ds} to {de}: treating as {{type}} occupations.'.format(
                ds=d_st.strftime('%Y-%m-%d'), de=d_en.strftime('%Y-%m-%d'))

        # Now apply the correct type of filtering for the period type.
        if s == 1:
            print(message.format(type='daily'))
            pxyz = process_daily_occups(pxyz)
        elif s == 2:
            print(message.format(type='continuous'))
            pxyz = process_cont_occups(pxyz)
        elif s == 0:
            print(message.format(type='empty/ignore'))
            pxyz = data_ok.iloc[0:0]
        else:
            raise ValueError('Unknown occupation type.')

        if pxyz is not None and len(pxyz) > 0:
            # Make sure that we only save back data for the period,
            # without any data which may have been prepended/appended
            # to help with filtering edge effects.
            out.append(pxyz[d_st:d_en])
    return out


# -

# ## Convert coordinates to local north-east-up
# This section calculates coordinates in metres relative to the installation origin of the site.

# +
origin_file = os.path.join(args.optspath, 'origin_%s.csv' %args.site)
if os.path.exists(origin_file):
    origin = pd.read_csv(origin_file).iloc[0]
elif input_type == 'ppp':
    # As gnss_ppp_vel.py: mean of first 100 epochs passing the (default) PPP filters.
    print('No origin_<site>.csv found: using mean of first 100 filtered PPP epochs as origin and saving')
    _o = filter_ppp(geod, config).iloc[0:100]
    origin = pp.calculate_local_origin(geod).iloc[0]
    
else:
    raise IOError(f'origin_<site>.csv file mandatory for TRACK inputs but not found ({origin_file}).')

x0, y0, z0, lat0, lon0 = origin['x0'], origin['y0'], origin['z0'], origin['lat0'], origin['lon0']

print('Converting to local North-East-Up')
neu = pp.calculate_local_neu(geod, x0, y0, z0, lat0, lon0)
geod_neu = pd.concat((geod, neu), axis=1)
# -

# ## Rotate to along-track (x) and across-track (y) displacement

# +
rfile = os.path.join(args.optspath, 'rotation_%s.dat' %args.site)
if os.path.exists(rfile):
    print('Loading existing rotation matrix')
    r1 = np.loadtxt(rfile)
else:
    if input_type == 'track':
        print('No rotation matrix file for site exists, creating using entire contents of GEOD file')
        directions = pp.calculate_displacement_trajectory(geod_neu)
    else:
        print('No rotation matrix file for site exists, creating using PPP epochs that pass filters')
        directions = pp.calculate_displacement_trajectory(filter_ppp(geod_neu, config))
    r1 = pp.create_rot_matrix(directions)
    os.makedirs(args.optspath, exist_ok=True)
    np.savetxt(rfile, r1)

print('Doing rotation')
xy = pp.rotate_to_displacements(geod_neu['East_m'], geod_neu['North_m'], r1)
geod_neu_xy = pd.concat((geod_neu, xy), axis=1)
# -

# ## Apply user pole corrections

# These corrections are based on already-rotated coordinates, NOT on North-East-Up
corrections_file = os.path.join(args.optspath, 'pole_corrections_%s.csv' %args.site)
if not args.nocorrect and os.path.exists(corrections_file):
    print('Applying pole corrections')
    geod_neu_xy = pp.correct_pole_changes(geod_neu_xy, corrections_file)

# ## Apply user exclusions

exclusions_file = os.path.join(args.optspath, 'exclusions_%s.csv' %args.site)
if not args.noexcl and os.path.exists(exclusions_file):
    print('Applying exclusions')
    geod_neu_xy = pp.apply_exclusions(geod_neu_xy, exclusions_file)
else:
    geod_neu_xy['exclude'] = False

geod_neu_xy

plt.figure()
geod_neu_xy.loc['2025-05'].N.plot(marker='.', linestyle='none')

# ## Apply filtering to each filter-parameters period

# ### Set up filter options per-period

# +
# Set up a Series to record the filter options set ID for each epoch.
filter_opts = pd.Series(0, geod_neu_xy.index)

# Keys that must be provided for each period.
mandatory_keys = ['date_start', 'date_finish']
# Filter sections that may be modified per period, by input type.
supported_keys = {
    'track': ['filter_positions_episodic', 'filter_positions_continuous', 'remove_displacement_outliers'],
    'ppp': ['filter_positions_ppp'],
}[input_type]

# The default set has ID=0
config_sets = {0: config}

# Subsequent filter sets begin at ID=1.
i = 1
if pfc is not None: 
    for period in pfc['periods']:
        config_here = deepcopy(config)
        for mk in mandatory_keys:
            if mk not in period.keys():
                raise ValueError(f'Parameter `{mk}` missing from period filter specification.')
            config_here[mk] = period[mk]
        for key in period.keys():
            if key not in (mandatory_keys + supported_keys):
                raise ValueError(f'Unsupported filter `{key}` found (supported filters for {input_type}: {supported_keys})')
        for key in supported_keys:
            if key in period:
                for subkey in period[key]:
                    config_here[key][subkey] = period[key][subkey]
        config_sets[i] = config_here
        filter_opts.loc[period['date_start']:period['date_finish']] = i
        i += 1

# Identify the distinct time periods for each filter options set
detect = np.abs(filter_opts.shift(1) - filter_opts)
dates = detect[detect > 0].index.to_list()
dates_start = deepcopy(dates)
dates_start.insert(0, geod_neu_xy.index[0])
filter_ids = filter_opts[dates_start]
dates.append(geod_neu_xy.index[-1])
filter_periods = list(zip(dates_start, dates, filter_ids))
# -

# ### Run the filtering

if args.stake:
    xyz = geod_neu_xy[geod_neu_xy.exclude == False].filter(items=('x_m', 'y_m', 'z_m'), axis='columns')
else:
    store = []
    for fp in filter_periods:
        fcfg = config_sets[fp[2]]
        data_here = geod_neu_xy.loc[fp[0]:fp[1]]
        print('')
        print('FILTER PARAMETERS PERIOD: {0}-{1}'.format(fp[0], fp[1]))
        print(fcfg)
        if input_type == 'track':
            store.extend(filter_track(data_here, fcfg))
        else:
            store.append(filter_ppp(data_here[data_here.exclude == False], fcfg))

    filtd = pd.concat(store, axis=0)
    if len(filtd) == 0:
        raise ValueError('No positions remain after filtering.')
    print('*** End of period-based processing ***')

# ## Smoothing the whole time series

filtd

if not args.stake:
    # check for duplicates, one or two epochs often introduced if using temporally varying window
    n = len(filtd)
    filtd = filtd.drop_duplicates()
    filtd = filtd[~filtd.index.duplicated()]
    print(f'Removed {n - len(filtd)} duplicates')

    # Restore to original frequency and interpolate; adds a flag column named 'interpolated'
    print('Regularising whole series')
    filtd_i = pp.regularise(filtd, args.sample_freq)

    # Do Gaussian filtering - this df does not have interpolated column
    print('Gaussian filtering whole series')
    filtd_disp = pp.smooth_displacement(filtd_i, 
                                        config['smooth_displacement']['gauss_win_secs'], 
                                        gauss_win_z_mult=config['smooth_displacement']['gauss_win_z_mult']
                                       )

    xyz = filtd_disp.filter(items=('x_m', 'y_m', 'z_m'), axis='columns')
    xyz['interpolated'] = filtd_i['interpolated'].astype(bool)

plt.figure()
geod_neu_xy.SigN_cm.plot(marker='.', linestyle='none')

# ## Calculate velocities

sig_n

if not args.stake:

    # Usually, set align to True to keep all timestamps aligned with midnight.
    # However, in edge cases of very patchy data, particualy on days 0-2 of a dataset,
    # setting this to False can allow data from day 0/1 to be retained that would otherwise
    # be clipped by pp.calculate_epoch_sigmas() (called by the wrapper function below).
    # This has the effect of introducing no-midnight timestamps into the velocity time series.
    align = True
    
    print('Calculating epoch-to-epoch velocities')
    # Supply the smoothed and interpolated x values, but the unsmoothed, uninterpolated sigma values.
    # Convert cm sigmas to metres
    sig_e = filtd['SigE_cm'] * 0.01
    sig_n = filtd['SigN_cm'] * 0.01
    v24h_epoch = pp.calculate_epoch_velocities_and_uncertainties(filtd_disp['x_m'], sig_e, sig_n, '1D', align_to_midnight=align)
    v5d_epoch = pp.calculate_epoch_velocities_and_uncertainties(filtd_disp['x_m'], sig_e, sig_n, '5D', align_to_midnight=align)
    v15d_epoch = pp.calculate_epoch_velocities_and_uncertainties(filtd_disp['x_m'], sig_e, sig_n, '15D', align_to_midnight=align)

if not args.stake and args.legacy:
    print('Calculating regularised velocities (legacy approach)')
    v24h_reg = pp.calculate_regular_velocities(filtd_disp['x_m'], '1D', tz=args.tz, method='epoch', sigmas=(sig_e, sig_n))
    v5d_reg = pp.calculate_regular_velocities(filtd_disp['x_m'], '5D', tz=args.tz, method='epoch', sigmas=(sig_e, sig_n))
    v15d_reg = pp.calculate_regular_velocities(filtd_disp['x_m'], '15D', tz=args.tz, method='epoch', sigmas=(sig_e, sig_n))
    maxperday = pd.Timedelta('1D') / pd.Timedelta(args.sample_freq)
    dayperc = 100 / maxperday * filtd_i.interpolated[filtd_i.interpolated == 0].resample('1D').count()
    dayperc.name = 'obs_cover_percent'
    v24h_reg = pd.concat((v24h_reg, dayperc), axis=1)

# ## Export to disk

# +
output_to_pre = '{site}_{ys}_{ds}_{ye}_{de}'.format(
    site=args.site,
    ys=geod.index[0].year,
    ds=geod.index[0].timetuple().tm_yday,
    ye=geod.index[-1].year,
    de=geod.index[-1].timetuple().tm_yday
)

# Other outputs are appended '_disp' rather than '_geod'.
output_L2_base = os.path.join(path_output_L2, f'{output_to_pre}_disp')
output_L2_H5 = f'{output_L2_base}{sfx}.h5'

os.makedirs(path_output_L2, exist_ok=True)

# If there is an existing file, delete it to prevent conflicts.
if os.path.exists(output_L2_H5):
    os.remove(output_L2_H5)
    print('Old main output file found, deleted.')
# -

# ### Save filters info

ffile = f'{output_L2_base}{sfx}_filter_parameters.yaml'
with open(ffile, 'w+') as fh:
    fh.write('# Record of the level-2 filtering parameters used to generate this Level-2 dataset. \n')
    fh.write(f'# Input type: {input_type}. Defaults file: {fn} \n')
    fh.write('# This is a reference-only file, generated from the defaults YAML and any user-specific YAML. \n')
    fh.write('# The default filter parameters are found in position 0. \n')
    fh.write('# Any periods in which different filter parameters were set are listed starting from position 1. \n')
    yaml.dump(config_sets, fh)

# ### Save displacements

xyz.to_hdf(output_L2_H5, key='xyz', format='table')
print('Saved displacements.')
print('Main output file: %s ' %output_L2_H5)

# ### Save velocities

if not args.stake:
    v24h_epoch.to_hdf(output_L2_H5, key='v_24h_epochs', format='table')
    v5d_epoch.to_hdf(output_L2_H5, key='v_5d_epochs', format='table')
    v15d_epoch.to_hdf(output_L2_H5, key='v_15d_epochs', format='table')
    v24h_epoch.to_csv(f'{output_L2_base}_velocity_24h_epochs{sfx}.csv')
    v5d_epoch.to_csv(f'{output_L2_base}_velocity_5d_epochs{sfx}.csv')
    v15d_epoch.to_csv(f'{output_L2_base}_velocity_15d_epochs{sfx}.csv')

    if args.legacy:
        v24h_reg.to_hdf(output_L2_H5, key='v_24h_legacy', format='table')
        v5d_reg.to_hdf(output_L2_H5, key='v_5d_legacy', format='table')
        v15d_reg.to_hdf(output_L2_H5, key='v_15d_legacy', format='table')
        v24h_reg.to_csv(f'{output_L2_base}_velocity_24h_legacy{sfx}.csv')
        v5d_reg.to_csv(f'{output_L2_base}_velocity_5d_legacy{sfx}.csv')
        v15d_reg.to_csv(f'{output_L2_base}_velocity_15d_legacy{sfx}.csv')
           
    if args.v6h:
        v_6h = pp.calculate_short_velocities(filtd_disp['x_m'], '6h')
        v_6h.to_hdf(output_L2_H5, key='v_6h', format='table')


# ## Diagnostic plots of final outputs

# +
if not args.noplot:
    try:
        import seaborn as sns
        sns.set_style('whitegrid')
    except ImportError:
        pass

do_plot = (not args.noplot) and (not args.stake)
plot_base = f'{output_L2_base}{sfx}'

label_geod = f'All epochs (Level-1 {input_type.upper()})'
label_xyz = 'Retained epochs (Level-2 XYZ)'
label_iterp = 'Filt./Smooth./Interp. (for L-2 Vel.)'


def ax_lim(data, scl_fac):
    """ Axis limits as mean +/- scl_fac * std. dev. """
    mn = np.nanmean(data)
    stdv = np.nanstd(data)
    return (mn - scl_fac * stdv, mn + scl_fac * stdv)


def shade_exclusions(ax):
    if os.path.exists(exclusions_file) and not args.noexcl:
        excl = pd.read_csv(exclusions_file, parse_dates=['excl_start', 'excl_end'])
        for ix, row in excl.iterrows():
            ax.axvspan(row.excl_start, row.excl_end, alpha=0.1, color='tab:red')


def epoch_plotting(ax, v_ts, data_kwargs=None, error_kwargs=None):
    # Plot stepped velocities
    ax.plot(v_ts.index, v_ts['v_myr'], drawstyle='steps-post', **data_kwargs)
    # Uncertainties are plotted separately at the mid-point of each (irregular) epoch.
    mid_pt_timestamps = (v_ts.index+np.abs(v_ts.index.diff(-1)/2))
    df_plotting = pd.DataFrame({'v_myr':v_ts.v_myr, 'v_unc':v_ts.v_uncertainty_myr})
    df_plotting.index = mid_pt_timestamps
    df_plotting = df_plotting[df_plotting.index.notnull()].dropna()
    ax.errorbar(df_plotting.index, df_plotting['v_myr'], linestyle='none',
                yerr=df_plotting['v_unc'], **error_kwargs)


def summer_years(ix):
    return range(ix.year.min(), ix.year.max())
# -

# ### For stakes

if not args.noplot and args.stake:
    fig, ax = plt.subplots()
    ax.plot(geod_neu_xy.x_m, geod_neu_xy.y_m, '.', color='gray', alpha=0.3, label='GEOD (after exclusions)')
    ax.set_title('Stake/Quick-Pos X-Y')
    fig.savefig(f'{plot_base}_xy.png', dpi=300)

# ### Positions

# Plot Y versus X
if do_plot:
    fig, ax = plt.subplots()
    ax.plot(geod_neu_xy.x_m, geod_neu_xy.y_m, '.', color='gray', alpha=0.3, label=label_geod)
    ax.plot(xyz.x_m, xyz.y_m, '.', color='tab:purple', alpha=0.3, label=label_xyz)
    ax.plot(filtd.x_m, filtd.y_m, '-', color='tab:blue', alpha=0.5, label=label_iterp)
    ax.set_ylim(ax_lim(geod_neu_xy.y_m, 3))
    ax.set_xlabel('Metres')
    ax.set_ylabel('Metres')
    ax.set_title(f'{args.site} Y - X')
    ax.legend()
    fig.savefig(f'{plot_base}_yx.png', dpi=300)

# Plot X, Y, Z versus time
if do_plot:
    for dim, lim in (('x', None), ('y', 3), ('z', 3)):
        col = f'{dim}_m'
        fig, ax = plt.subplots()
        shade_exclusions(ax)
        ax.plot(geod_neu_xy.index, geod_neu_xy[col], '.', color='gray', alpha=0.3, label=label_geod)
        ax.plot(xyz[xyz.interpolated==False].index, xyz[xyz.interpolated==False][col], '.', color='tab:purple', alpha=0.3, label=label_xyz)
        ax.plot(filtd_disp.index, filtd_disp[col], '-', color='tab:blue', alpha=0.5, label=label_iterp)
        if lim is not None:
            ax.set_ylim(ax_lim(geod_neu_xy[col], lim))
        ax.set_ylabel('Metres')
        ax.set_title(f'{args.site} {dim.upper()} - Time')
        ax.legend()
        fig.savefig(f'{plot_base}_{dim}t.png', dpi=300)

# ### Velocities (all)

if do_plot and args.legacy:
    fig, ax = plt.subplots()
    ax.errorbar(v24h_reg.index+pd.Timedelta(hours=12), v24h_reg.v_myr, yerr=v24h_reg.v_uncertainty_myr, elinewidth=1.4, ecolor='tab:blue', drawstyle='steps-mid', alpha=0.5)
    ax.errorbar(v5d_reg.index+pd.Timedelta(hours=(5*24)/2), v5d_reg.v_myr, yerr=v5d_reg.v_uncertainty_myr, elinewidth=1, color='k', ecolor='k', drawstyle='steps-mid', linewidth=2)
    ax.errorbar(v15d_reg.index+pd.Timedelta(hours=(15*24)/2), v15d_reg.v_myr, yerr=v15d_reg.v_uncertainty_myr, elinewidth=1, color='tab:red', ecolor='tab:red', drawstyle='steps-mid', linewidth=2)
    ax.set_ylim(ax_lim(v24h_reg.v_myr, 10))
    ax.set_title(f'{args.site} 24-H, 5-D and 15-D velocity (legacy differencing)')
    ax.set_ylabel('m/yr')
    fig.savefig(f'{plot_base}_v24h_5d_legacy.png', dpi=300)

if do_plot:
    fig, ax = plt.subplots()
    epoch_plotting(ax, v24h_epoch, 
                    data_kwargs=dict(color='tab:blue'),
                    error_kwargs=dict(elinewidth=1, ecolor='tab:blue', capsize=0, alpha=0.5))
    epoch_plotting(ax, v5d_epoch, 
                    data_kwargs=dict(color='k', linewidth=2),
                    error_kwargs=dict(elinewidth=1, ecolor='k', capsize=1))
    epoch_plotting(ax, v15d_epoch, 
                    data_kwargs=dict(color='tab:red', linewidth=2),
                    error_kwargs=dict(elinewidth=1, ecolor='tab:red', capsize=1))
    ax.set_ylim(ax_lim(v24h_epoch.v_myr, 10))
    ax.set_title(f'{args.site} 24-H, 5-D and 15-D velocity (observational epoch differencing)')
    ax.set_ylabel('m/yr')
    fig.savefig(f'{plot_base}_v24h_5d_epochs.png', dpi=300)

# ### Velocities (summer only)

if do_plot and args.legacy:
    for year in summer_years(v24h_reg.index):
        v24h_here = v24h_reg.loc[f'{year}-05-01':f'{year}-10-01']
        if len(v24h_here) == 0 or v24h_here.obs_cover_percent.mean() <= 0.1:
            continue
        v5d_here = v5d_reg.loc[f'{year}-05-01':f'{year}-10-01']
        v15d_here = v15d_reg.loc[f'{year}-05-01':f'{year}-10-01']
        fig, ax = plt.subplots()
        ax.errorbar(v24h_here.index+pd.Timedelta(hours=12), v24h_here.v_myr, yerr=v24h_here.v_uncertainty_myr, elinewidth=0.2, ecolor='tab:blue', drawstyle='steps-mid', alpha=0.5)
        ax.errorbar(v5d_here.index+pd.Timedelta(hours=(5*24)/2), v5d_here.v_myr, yerr=v5d_here.v_uncertainty_myr, elinewidth=1, color='k', ecolor='k', drawstyle='steps-mid', linewidth=2)
        ax.errorbar(v15d_here.index+pd.Timedelta(hours=(15*24)/2), v15d_here.v_myr, yerr=v15d_here.v_uncertainty_myr, elinewidth=1, color='tab:red', ecolor='tab:red', drawstyle='steps-mid', linewidth=2)
        ax.set_xlim(pd.Timestamp(year, 5, 1), pd.Timestamp(year, 10, 1))
        ax.set_ylim(ax_lim(v24h_reg.v_myr, 10))
        ax.set_title(f'{args.site} 24-H, 5-D and 15-D velocity, Summer {year} (legacy differencing)')
        ax.set_ylabel('m/yr')
        fig.savefig(f'{plot_base}_v24h_5d_summer_{year}_legacy.png', dpi=300)

if do_plot:
    for year in summer_years(v24h_epoch.index):
        v24h_here = v24h_epoch.loc[f'{year}-05-01':f'{year}-10-01']
        if len(v24h_here) == 0:
            continue
        v5d_here = v5d_epoch.loc[f'{year}-05-01':f'{year}-10-01']
        v15d_here = v15d_epoch.loc[f'{year}-05-01':f'{year}-10-01']
        fig, ax = plt.subplots()
        epoch_plotting(ax, v24h_here, 
                data_kwargs=dict(color='tab:blue', alpha=0.5),
                error_kwargs=dict(elinewidth=1, ecolor='tab:blue', capsize=0, alpha=0.5))
        epoch_plotting(ax, v5d_here, 
                        data_kwargs=dict(color='k', linewidth=2),
                        error_kwargs=dict(elinewidth=1, ecolor='k', capsize=1))
        epoch_plotting(ax, v15d_here, 
                        data_kwargs=dict(color='tab:red', linewidth=2),
                        error_kwargs=dict(elinewidth=1, ecolor='tab:red', capsize=1))
        ax.set_xlim(pd.Timestamp(year, 5, 1), pd.Timestamp(year, 10, 1))
        ax.set_ylim(ax_lim(v24h_epoch.v_myr, 10))
        ax.set_title(f'{args.site} 24-H, 5-D and 15-D velocity, Summer {year} (observational epoch differencing)')
        ax.set_ylabel('m/yr')
        fig.savefig(f'{plot_base}_v24h_5d_summer_{year}_epochs.png', dpi=300)

# ### 6-h velocities

if do_plot and args.v6h:
    fig, ax = plt.subplots()
    v_6h.plot(ax=ax)
    ax.set_title(f'{args.site} 6-H velocity')
    ax.set_ylabel('m/yr')
    fig.savefig(f'{plot_base}_v6h.png', dpi=300)


